source 'http://rubygems.org'

gem 'faraday'
gem 'faraday-multipart'
gem 'puma'
gem 'rackup'
gem 'rack-flash3'
gem 'sinatra'

group :development, :test do
  gem 'byebug'
end

group :test do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec'
  gem 'selenium-webdriver'
end