version: "3.8"

services:
  app:
    build: .
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - net
    ports:
      - "4567:4567"
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - net
    environment:
      POSTGRES_USER: relabs
      POSTGRES_PASSWORD: relabs
    
networks:
  net:
    driver: bridge
