version: "3.8"

services:
  backend:
    build: ./backend
    container_name: server
    working_dir: /app
    volumes:
      - ./backend:/app
    networks:
      - net
    ports:
      - "4567:4567"
    depends_on:
      - database
  frontend:
    build: ./frontend
    container_name: app
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - net
    ports:
      - "3000:3000"
    depends_on:
      - database
      - backend
  database:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/persistence/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net
    environment:
      POSTGRES_USER: relabs
      POSTGRES_PASSWORD: relabs
    
networks:
  net:
    driver: bridge

volumes:
  pg_data:
    driver: local