source 'http://rubygems.org'

gem 'csv'
gem 'pg'
gem 'puma'
gem 'rackup'
gem 'rake'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-cors'

group :development, :test do
  gem 'byebug'
end

group :test do
  gem 'capybara'
  gem 'rack-test'
  gem 'rspec'
  gem 'selenium-webdriver'
end