require_relative 'services/tests_service'
require_relative 'jobs/import_job'

desc 'Importar dados de exames de data.csv'

namespace :data do
  task :import do
    puts '=== Importando dados ==='
    ImportJob.perform(file: File.open(File.join(__dir__, 'persistence', 'data.csv')))
    puts '=== Import concluído ==='
  end
end
